spring:
  application:
    name: order-inventory

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:h2:mem:shopflow;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: 172.23.34.188:9092
    consumer:
      group-id: order-inventory
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 1
      properties:
        max.block.ms: 1000
        request.timeout.ms: 1000
        delivery.timeout.ms: 3000

server:
  port: 8080

shopflow:
  redis:
    redisson:
      enabled: true
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout-ms: 3000
    lock:
      wait-time-ms: 1000
      lease-time-ms: 3000
  sample-data:
    enabled: true
  kafka:
    topics:
      order-events: shopflow.order-events
  outbox:
    publisher:
      max-retry-count: 3
      scheduler:
        enabled: true
        fixed-delay-ms: 1000
        initial-delay-ms: 3000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
